version: '3'

volumes:
  mosquitto_data:

services:
  mosquitto:
    image: eclipse-mosquitto:2.0.15
    volumes:
      - ./mosquitto.conf:/mosquitto/config/mosquitto.conf
      - ./mosquitto_passwd:/mosquitto/config/password_file
      - mosquitto_data:/mosquitto/data
    ports:
      - 1883:1883
    deploy:
      mode: replicated
      replicas: 1
      restart_policy:
        condition: on-failure
      resources:
        limits:
          cpus: '0.5'
          memory: 512M
        reservations:
          cpus: '0.25'
          memory: 128M
